# Generated by Django 3.0.3 on 2020-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_number', models.CharField(max_length=64)),
                ('start_date', models.CharField(max_length=4)),
                ('end_date', models.CharField(max_length=4)),
            ],
        ),
    ]
